trigger:
- main
 
resources:
- repo: self
 
variables:
  tag: '$(Build.BuildId)'
 
stages:
- stage: Build
  displayName: Build and Push Docker Image
  jobs:
  - job: Build
    displayName: Build and Push
    pool:
      vmImage: ubuntu-latest
    steps:
    - task: Docker@2
      displayName: Login to Docker Hub
      inputs:
        containerRegistry: 'saiteja8747/testapp'
        command: 'login'
 
    - task: Docker@2
      displayName: Build and Push Docker Image
      inputs:
        containerRegistry: 'saiteja8747/testapp'
        repository: 'saiteja8747/testapp'
        command: 'buildAndPush'
        Dockerfile: '**/Dockerfile'
        tags: |
          $(tag)
          latest